"use strict";

window.LEARNING_CONTENT = {
  worlds: [
    {
      id: "hebrew",
      name: "שער עברית",
      color: "#2f6f5e",
      x: 2,
      y: 2,
      challengeIds: ["dag", "bayit"],
    },
    {
      id: "vowels",
      name: "מערת הניקוד",
      color: "#d28b27",
      x: 5,
      y: 3,
      challengeIds: ["shalom", "sefer"],
    },
    {
      id: "english",
      name: "English Tower",
      color: "#347da5",
      x: 8,
      y: 2,
      challengeIds: ["cat", "sun"],
    },
  ],
  challenges: {
    dag: {
      world: "עברית",
      title: "בונים מילה קצרה",
      target: "דָּג",
      letters: ["ג", "דָּ"],
      answer: "דָּג",
      direction: "rtl",
      rule: "בעברית קוראים מימין לשמאל. כאן מחברים צליל פותח דָּ ואז צליל סוגר ג.",
      hint: "האות הראשונה בצד ימין היא דָּ.",
    },
    bayit: {
      world: "עברית",
      title: "מקלידים מילה מנוקדת",
      target: "בַּיִת",
      letters: ["ת", "יִ", "בַּ"],
      answer: "בַּיִת",
      direction: "rtl",
      rule: "מילה ארוכה יותר נבנית מחלקים קטנים: בַּ + יִ + ת.",
      hint: "נסה/י לבנות: בַּ ואז יִ ואז ת.",
    },
    shalom: {
      world: "ניקוד",
      title: "מזהים תנועות במילה",
      target: "שָׁלוֹם",
      letters: ["ם", "וֹ", "ל", "שָׁ"],
      answer: "שָׁלוֹם",
      direction: "rtl",
      rule: "הניקוד עוזר לקרוא את הצליל המדויק. שָׁ נשמע כמו sha, ו־וֹ נשמע כמו o.",
      hint: "התחל/י ב־שָׁ וסיים/י ב־ם.",
    },
    sefer: {
      world: "ניקוד",
      title: "מילה עם שתי הברות",
      target: "סֵפֶר",
      letters: ["ר", "פֶ", "סֵ"],
      answer: "סֵפֶר",
      direction: "rtl",
      rule: "כשמילה קשה, מפרקים אותה להברות קטנות: סֵ + פֶ + ר.",
      hint: "ההברה הראשונה היא סֵ.",
    },
    cat: {
      world: "English",
      title: "Build a CVC word",
      target: "cat",
      letters: ["t", "a", "c"],
      answer: "cat",
      direction: "ltr",
      rule: "English CVC words use consonant + vowel + consonant. Blend c + a + t into cat.",
      hint: "Start with c, then a, then t.",
    },
    sun: {
      world: "English",
      title: "Type and build",
      target: "sun",
      letters: ["n", "s", "u"],
      answer: "sun",
      direction: "ltr",
      rule: "Blend each sound slowly: s + u + n. Then read the whole word.",
      hint: "The first sound is s.",
    },
  },
};
